#server port
server:
  port: 8761
#It is not a client, it is a server : http://localhost:8761/dashboard
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
#application name

  application:
    name: SERVER-REGISTRY